variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube
  - docker-deployment

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./gradlew clean test jacocoTestReport
    - ./gradlew sonar "-Dsonar.host.url=http://localhost:9000" "-Dsonar.token=sqp_ab081c3f006c878cc86b67183266b9db765a4133" "-Dsonar.qualitygate.wait=true"
  allow_failure: false

docker-deployment:
  stage: docker-deployment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - ./gradlew clean assemble
    - docker stop carenest-backend-staging || true
    - docker rm carenest-backend-staging || true
    - docker rmi carenest-backend || true
    - docker build -t carenest-backend -f Dockerfile .
    - docker run -d -p 8090:8080 --net=docker_careNest_network_staging --env spring_profiles_active=staging --name=carenest-backend-staging carenest-backend
  only:
    - main
